### ISSUE TITLE
How the drink information is displayed..

### ISSUE THREAD

**Issue by justnle** [agtravis/pocket-bartender#14]
Instead of dumping all of the information for various drinks and recipes after clicking, we could clean it up a bit with the following sequence:

Liquor info submitted...

1. Click 'Display Info'
2. Just the names of the cocktails are displayed in a list, perhaps with pictures as well
3. User can 'choose' which one they want to make with a 'make this drink' button?
4. 'Make this drink' will then display the recipe for that cocktail

Could help with the backend for implementing the nutritionix api..
Once the user clicks make this drink, the ingredients could be passed to an array, which we can then pass the array elements to the nutrionix api calls and get the information that way.

Just an idea of how to make implementation of the second api a little easier!

**Comment by agtravis** [comment]
I like that a lot. The previous mess was just me playing around and taking stuff from the response, I'm not attached to any of it.

Would be cool to implement the PDF api as you mentioned before, perhaps with a 'print' button as well directly in the app. If we have time...

**Comment by justnle** [comment]
Sounds great, I am going to start some of that functionality then.

The PDF api was looking promising but they only offer a trial, otherwise it costs something like $10 a month. Will explore other APIs later though!

**Comment by agtravis** [comment]
Sounds good. In case you didn't see yet I have created a class '.hide' and am just applying and removing that class to elements on 'click' events basically, this can be applied to anything. I just got the background image working on the cabinet, and I'm done for the night now. have fun!
