### ISSUE TITLE
Duplicate 'make this drink' buttons/notes

### ISSUE THREAD

**Issue by agtravis** [agtravis/pocket-bartender#17]
I like the ability to display the recipe on further click. 

_"I think ideally I would want to make clicking the 'Make this drink' button a second time hide the recipe in case the user changes their mind, but I can work on that later."_

Or maybe make this drink shows recipe in a new modal pop up? or there is a hide button that appears when the recipe shows?

=====================

When you chose a second liquor to display info without refreshing, the make this drink parent div needs to empty before a new button is added. 

Also, I need to write a few lines of code to handle a 404 response. For example I've added 'cola' to my liquor cabinet on my personal local storage, and it displays an image of a can of coke, but it doesn't render any cocktails. Since some ingredients can be added to liquorCabinet but won't generate recipes, we should discuss how to manage that - there are basically 2 404s: no ingredient, and no recipe.

**Comment by justnle** [comment]
I noticed it kept adding the buttons a little later after testing it more, that is fixed now with the latest pull request. 

We can use a modal for the drink information if you guys want. Will discuss further tomorrow in class
